air_defence/urls.py
from django.contrib import admin
from django.urls import path, include
from defence import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('defence.urls')),
    path('defence/',include(('defence.urls','defence'),namespace='defence.urls')),
    
    path('uaccount/',include(('uaccount.urls','uaccount'),namespace='uaccount.urls')),
    path('uaccounts/',include('django.contrib.auth.urls'))

]

defence/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('home', views.home,name='home'),
    path('exam',views.exam,name='exam'),
    path('health',views.health,name='health'),
    path('canteen',views.canteen,name='canteen'),
    path('userleave',views.userleave,name='userleave'),
    path('event',views.event,name='event'), 
    path('userprofile',views.userprofile,name='userprofile'),
    path('adm',views.adm,name='adm'),
    path('admhome',views.admhome,name='admhome'),
    path('profileadm',views.profileadm,name='profileadm'),
    path('admevent',views.admevent,name='admevent'),
    path('healthadm',views.healthadm,name='healthadm'),
    path('approvels',views.approvels,name='approvels'),
    path('leaveadm',views.leaveadm,name='leaveadm'),
    path('appointments',views.appointments,name='appointments'),
    path('notification',views.notification,name='notification'),
    path('seo',views.seo,name='seo'),
    path('seohome',views.seohome,name='seohome'),
    path('leaveseo',views.leaveseo,name='leaveseo'),
    path('seoevent',views.seoevent,name='seoevent'),
    path('healthseo',views.healthseo,name='healthseo'),
    path('profileseo',views.profileseo,name='profileseo'),
    path('seoexam',views.seoexam,name='seoexam'),
    path('adddoctor',views.adddoctor,name='adddoctor'),
    path('canteenprofile',views.canteenprofile,name='canteenprofile'), 
    path('healthcanteen',views.healthcanteen,name='healthcanteen'),
    path('canteenlg',views.canteenlg,name='canteenlg'),
    path('canteenhm',views.canteenhm,name='canteenhm'),
    path('canteenevent',views.canteenevent,name='canteenevent'),
    path('canteenexam',views.canteenexam,name='canteenexam'),
    path('canteenleave',views.canteenleave,name='canteenleave'),
    path('addfood',views.addfood,name='addfood'),
   
   
   
     
]

uaccount/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('addairman',views.addairman,name='addairman'),
    path('user',views.user,name='user'),
       
]

defence/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.models import auth,User
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
@login_required
def home(request):
    return render(request,'defence/main.html')

@login_required
def profileadm(request):
    return render(request,'defence/profileadm.html')

@login_required
def profileseo(request):
    return render(request,'defence/profileseo.html')

@login_required
def canteenprofile(request):
    return render(request,'defence/canteenprofile.html')


def canteen(request):
    return render(request,'defence/canteentest.html')

@login_required
def exam(request):
    return render(request,'defence/exam.html')

@login_required
def approvels(request):
    return render(request,'defence/approvels.html')

@login_required
def addfood(request):
    return render(request,'defence/addfood.html')

@login_required
def appointments(request):
    return render(request,'defence/appoinments.html')

@login_required
def notification(request):
    return render(request,'defence/notification.html')

@login_required
def seoexam(request):
    return render(request,'defence/seoexam.html')

@login_required
def canteenexam(request):
    return render(request,'defence/canteenexam.html')

@login_required
def adddoctor(request):
    return render(request,'defence/adddoctor.html')

def index(request):
    return render(request,'defence/index.html')

@login_required
def admhome(request):
         return render(request,'defence/admhome.html')

@login_required
def event(request):
    return render(request,'defence/events.html')

@login_required
def admevent(request):
    return render(request,'defence/admevent.html')

@login_required
def seoevent(request):
    return render(request,'defence/seoevent.html')

@login_required
def canteenevent(request):
    return render(request,'defence/canteenevent.html')


@login_required
def healthadm(request):
    return render(request,'defence/healthadm.html')

@login_required    
def healthseo(request):
    return render(request,'defence/healthseo.html')

@login_required
def healthcanteen(request):
    return render(request,'defence/healthcanteen.html')

@login_required
def health(request):
    return render(request,'defence/health.html')

@login_required
def seohome(request):
    return render(request,'defence/Seohome.html')

@login_required
def canteenleave(request):
    return render(request,'defence/canteenleave.html')

@login_required
def leaveadm(request):
    return render(request,'defence:leaveadm.html')


def seo(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None and user.id==2:
            auth.login(request,user)
            return redirect('seohome')
        else:
            messages.info(request,'invalid entry')
            return redirect('seo')
    else:

        return render(request,'defence/Login_as_Seo.html')


def adm(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None and user.id==1:
            auth.login(request,user)
            return redirect('admhome')
        else:
            messages.info(request,'invalid entry')
            return redirect('adm')
    else:

        return render(request,'defence/Login_as_Admin.html')

@login_required
def userprofile(request):
    return render(request,'defence/userprofile.html')

@login_required
def canteenhm(request):
    return render(request,'defence/canteenhm.html')

@login_required
def userleave(request):
    return render(request,'defence/userleave.html')

@login_required
def leaveseo(request):
    return render(request,'defence/leaveseo.html')





def canteenlg(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None and user.id==3:
            auth.login(request,user)
            return redirect('canteenhm')
        else:
            messages.info(request,'invalid entry')
            return redirect('canteenlg')
    else:

        return render(request,'defence/Login_as_Canteen.html')

defence/templates/defence/appoinments.html
{%  load static %}
{% load crispy_forms_tags%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>DATABASE OF INDIAN AMRY</title>

  <!-- css -->
  <link href="{% static 'defence/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'defence/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" type="text/css" href="{% static 'defence/plugins/cubeportfolio/css/cubeportfolio.min.css' %}">
  <link href="{% static 'defence/css/nivo-lightbox.css' %}" rel="stylesheet" />
  <link href="{% static 'defence/css/nivo-lightbox-theme/default/default.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'defence/css/owl.carousel.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'defence/css/owl.theme.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'defence/css/animate.css' %}" rel="stylesheet" />
  <link href="{% static 'defence/css/style.css' %}" rel="stylesheet">

  <!--APPOINMENTS-->
  <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
-->


  <!-- boxed bg -->
  <link id="bodybg" href="{% static 'defence/bodybg/bg1.css' %}" rel="stylesheet" type="text/css" />
  <!-- template skin -->
  <link id="t-colors" href="{% static 'defence/color/default.css'%}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Medicio
    Theme URL: https://bootstrapmade.com/medicio-free-bootstrap-theme/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-custom"> 


  <div id="wrapper">

    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="top-area">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-md-6">
              <p class="bold text-left">INDIAN ARMY </p>
            </div>
            <div class="col-sm-6 col-md-6">
              <p class="bold text-right">Service Before Self</p>
            </div>
          </div>
        </div>
      </div>
      <div class="container navigation">

        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>s
                </button>
          <a class="navbar-brand" href="index.html">
                    <img src="{% static 'defence/img/logo.jpg' %}" alt="" width="150" height="40" />
                </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{%url 'defence:admhome'%}">Home</a></li>
            <li><a href="#service">PROFILE</a></li>
            <li><a href="{%url 'defence:healthadm'%}">HEALTH</a></li>
            <li><a href="{%url 'defence:admevent'%}">EVENTS</a></li>
            <li><a href="{%url 'uaccount:addairman'%}">ADD AIRMAN</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="badge custom-badge red pull-right">Extra</span>More <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{%url 'defence:approvels'%}">APPROVELS</a></li>
                <li><a href="{%url 'defence:appointments'%}">APPOINMENTS</a></li>
                <li><a href="{%url 'defence:notification'%}" class="notification">NOTIFICATIONS
                <span class="badge">3</span></a></li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>
    <br><br><br><br><br><br>
     <div class="container">

        <div class="row" style="padding: 10px;">
            
            <div class="col-12">
               <h2 style="color:#000080">APPOINMENTS</h2>
               <hr>
            </div>
        </div>


        <div class="card" style="background-color: azure;
        padding-left: 25px;
        padding-top: 10px;
        padding-right: 25px;
        padding-bottom: 10px;">
            <div class="card-body">
              <h4 class="card-title">Appointment with SEO Admin</h4>
              <p class="card-text">You have an Appointments with SEO admin about medical issues at 10:00am Today</p>
              <a href="#" class="card-link">Click to check for details</a>
            </div>
        </div>

        <div class="row">&nbsp;</div>

        <div class="card" style="background-color: azure;
        padding-left: 25px;
        padding-top: 10px;
        padding-right: 25px;
        padding-bottom: 10px;">
            <div class="card-body">
              <h4 class="card-title">New join</h4>
              <p class="card-text">You have an appoinment with new joiners "A talk with future" at 11:00am Today</p>
              <a href="#" class="card-link">Click for details</a>
            </div>
        </div>

        <div class="row">&nbsp;</div>

        <div class="card" style="background-color: azure;
        padding-left: 25px;
        padding-top: 10px;
        padding-right: 25px;
        padding-bottom: 10px;">
            <div class="card-body">
              <h4 class="card-title">Appointments with Canteen Admin</h4>
              <p class="card-text">You have an Appointments with canteen admin about food safety at 2:30pm Today</p>
              <a href="#" class="card-link">Click to check the food details</a>
            </div>
        </div>

        <div class="row">&nbsp;</div>

        <div class="card" style="background-color: azure;
        padding-left: 25px;
        padding-top: 10px;
        padding-right: 25px;
        padding-bottom: 10px;">
            <div class="card-body">
              <h4 class="card-title">Inaguration</h4>
              <p class="card-text">You have an inaguration on Tommorow with SEO Admin </p>
              <a href="#" class="card-link">Click for details</a>
            </div>
        </div>

        <div class="row">&nbsp;</div>

        <div class="card" style="background-color: azure;
        padding-left: 25px;
        padding-top: 10px;
        padding-right: 25px;
        padding-bottom: 10px;">
            <div class="card-body">
              <h4 class="card-title">Meeting With PM</h4>
              <p class="card-text">You have an Appoinment with Prime Minister at 3:00 pm Today </p>
              <a href="#" class="card-link">Click for details</a>
            </div>
        </div>
    
    </div>


    <footer>

      <div class="container">
        <div class="row">
          <div class="col-sm-6 col-md-4">
            <div class="wow fadeInDown" data-wow-delay="0.1s">
              <div class="widget">
                <h5>About Medicio</h5>
                <p>
                  Lorem ipsum dolor sit amet, ne nam purto nihil impetus, an facilisi accommodare sea
                </p>
              </div>
            </div>
            <div class="wow fadeInDown" data-wow-delay="0.1s">
              <div class="widget">
                <h5>Information</h5>
                <ul>
                  <li><a href="#">Home</a></li>
                  <li><a href="#">Laboratory</a></li>
                  <li><a href="#">Medical treatment</a></li>
                  <li><a href="#">Terms & conditions</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="wow fadeInDown" data-wow-delay="0.1s">
              <div class="widget">
                <h5>Medicio center</h5>
                <p>
                  Nam leo lorem, tincidunt id risus ut, ornare tincidunt naqunc sit amet.
                </p>
                <ul>
                  <li>
                    <span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-calendar-o fa-stack-1x fa-inverse"></i>
								</span> Monday - Saturday, 8am to 10pm
                  </li>
                  <li>
                    <span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-phone fa-stack-1x fa-inverse"></i>
								</span> +62 0888 904 711
                  </li>
                  <li>
                    <span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-envelope-o fa-stack-1x fa-inverse"></i>
								</span> hello@medicio.com
                  </li>

                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="wow fadeInDown" data-wow-delay="0.1s">
              <div class="widget">
                <h5>Our location</h5>
                <p>The Suithouse V303, Kuningan City, Jakarta Indonesia 12940</p>

              </div>
            </div>
            <div class="wow fadeInDown" data-wow-delay="0.1s">
              <div class="widget">
                <h5>Follow us</h5>
                <ul class="company-social">
                  <li class="social-facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li class="social-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li class="social-google"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                  <li class="social-vimeo"><a href="#"><i class="fa fa-vimeo-square"></i></a></li>
                  <li class="social-dribble"><a href="#"><i class="fa fa-dribbble"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="sub-footer">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6">
              <div class="wow fadeInLeft" data-wow-delay="0.1s">
                <div class="text-left">
                  <p>&copy;Copyright - Medicio Theme. All rights reserved.</p>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
              <div class="wow fadeInRight" data-wow-delay="0.1s">
                <div class="text-right">
                  <div class="credits">
                    <!--
                      All the links in the footer should remain intact. 
                      You can delete the links only if you purchased the pro version.
                      Licensing information: https://bootstrapmade.com/license/
                      Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Medicio
                    -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div><br>
    </footer>

  </div>
  <a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>

  <!-- Core JavaScript Files -->
  <script src="{%  static 'defence/js/jquery.min.js' %}"></script>
  <script src="{%  static 'defence/js/bootstrap.min.js' %}"></script>
  <script src="{%  static 'defence/js/jquery.easing.min.js' %}"></script>
  <script src="{%  static 'defence/js/wow.min.js' %}"></script>
  <script src="{%  static 'defence/js/jquery.scrollTo.js' %}"></script>
  <script src="{%  static 'defence/js/jquery.appear.js' %}"></script>
  <script src="{%  static 'defence/js/stellar.js' %}"></script>
  <script src="{%  static 'defence/plugins/cubeportfolio/js/jquery.cubeportfolio.min.js' %}"></script>
  <script src="{%  static 'defence/js/owl.carousel.min.js' %}"></script>
  <script src="{%  static 'defence/js/nivo-lightbox.min.js' %}"></script>
  <script src="{%  static 'defence/js/custom.js' %}"></script>

</body>
</html>

defence/templates/defence/profileadm.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>DATABASE OF INDIAN AMRY</title>

  <!-- css -->
  <link href="{% static 'defence/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'defence/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" type="text/css" href="{% static 'defence/plugins/cubeportfolio/css/cubeportfolio.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'defence/plugins/cubeportfolio/css/profile.css' %}">
  <link href="{% static 'defence/css/nivo-lightbox.css' %}" rel="stylesheet" />
  <link href="{% static 'defence/css/nivo-lightbox-theme/default/default.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'defence/css/owl.carousel.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'defence/css/owl.theme.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'defence/css/animate.css' %}" rel="stylesheet" />
  <link href="{% static 'defence/css/style.css' %}" rel="stylesheet">

  <!-- boxed bg -->
  <link id="bodybg" href="{% static 'defence/bodybg/bg1.css' %}" rel="stylesheet" type="text/css" />
  <!-- template skin -->
  <link id="t-colors" href="{% static 'defence/color/default.css'%}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Medicio
    Theme URL: https://bootstrapmade.com/medicio-free-bootstrap-theme/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-custom">


  <div id="wrapper">

    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="top-area">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-md-6">
              <p class="bold text-left">INDIAN ARMY </p>
            </div>
            <div class="col-sm-6 col-md-6">
              <p class="bold text-right">Service Before Self</p>
            </div>
          </div>
        </div>
      </div>
      <div class="container navigation">

        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>s
                </button>
          <a class="navbar-brand" href="index.html">
                    <img src="{% static 'defence/img/logo.jpg' %}" alt="" width="150" height="40" />
                </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{%url 'defence:admhome'%}">Home</a></li>
            <li><a href="{%url 'defence:profileadm'%}">PROFILE</a></li>
            <li><a href="{%url 'defence:healthadm'%}">HEALTH</a></li>
            <li><a href="{%url 'defence:admevent'%}">EVENTS</a></li>
            <li><a href="{%url 'uaccount:addairman'%}">ADD AIRMAN</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="badge custom-badge red pull-right">Extra</span>More <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{%url 'defence:approvels'%}">APPROVELS</a></li>
                <li><a href="{%url 'defence:appointments'%}">APPOINMENTS</a></li>
                <<li><a href="{%url 'defence:notification'%}" class="notification">NOTIFICATIONS
                <span class="badge">3</span></a></li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>
    <br><br><br><br><br><br><br><br>
    
<div class="card">
  <img src="{% static 'defence/img/team/A1.jpg' %}" alt="John" style="width:100%">
  <h1>Harindar Singh</h1>
  <b><p class="title">Admin,Lt Gen</p></b>
  <p>Maratha Light Infantry
  </p>
  <a href="#"><i class="fa fa-dribbble"></i></a>
  <a href="#"><i class="fa fa-twitter"></i></a>
  <a href="#"><i class="fa fa-linkedin"></i></a>
  <a href="#"><i class="fa fa-facebook"></i></a>
  <p><button>Contact</button></p>
</div>
    <footer>

      <div class="container">
        <div class="row">
          <div class="col-sm-6 col-md-4">
            <div class="wow fadeInDown" data-wow-delay="0.1s">
              <div class="widget">
                <h5>About Medicio</h5>
                <p>
                  Lorem ipsum dolor sit amet, ne nam purto nihil impetus, an facilisi accommodare sea
                </p>
              </div>
            </div>
            <div class="wow fadeInDown" data-wow-delay="0.1s">
              <div class="widget">
                <h5>Information</h5>
                <ul>
                  <li><a href="#">Home</a></li>
                  <li><a href="#">Laboratory</a></li>
                  <li><a href="#">Medical treatment</a></li>
                  <li><a href="#">Terms & conditions</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="wow fadeInDown" data-wow-delay="0.1s">
              <div class="widget">
                <h5>Medicio center</h5>
                <p>
                  Nam leo lorem, tincidunt id risus ut, ornare tincidunt naqunc sit amet.
                </p>
                <ul>
                  <li>
                    <span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-calendar-o fa-stack-1x fa-inverse"></i>
								</span> Monday - Saturday, 8am to 10pm
                  </li>
                  <li>
                    <span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-phone fa-stack-1x fa-inverse"></i>
								</span> +62 0888 904 711
                  </li>
                  <li>
                    <span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-envelope-o fa-stack-1x fa-inverse"></i>
								</span> hello@medicio.com
                  </li>

                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-4">
            <div class="wow fadeInDown" data-wow-delay="0.1s">
              <div class="widget">
                <h5>Our location</h5>
                <p>The Suithouse V303, Kuningan City, Jakarta Indonesia 12940</p>

              </div>
            </div>
            <div class="wow fadeInDown" data-wow-delay="0.1s">
              <div class="widget">
                <h5>Follow us</h5>
                <ul class="company-social">
                  <li class="social-facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li class="social-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li class="social-google"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                  <li class="social-vimeo"><a href="#"><i class="fa fa-vimeo-square"></i></a></li>
                  <li class="social-dribble"><a href="#"><i class="fa fa-dribbble"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="sub-footer">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6">
              <div class="wow fadeInLeft" data-wow-delay="0.1s">
                <div class="text-left">
                  <p>&copy;Copyright - Medicio Theme. All rights reserved.</p>
                </div>
              </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
              <div class="wow fadeInRight" data-wow-delay="0.1s">
                <div class="text-right">
                  <div class="credits">
                    <!--
                      All the links in the footer should remain intact. 
                      You can delete the links only if you purchased the pro version.
                      Licensing information: https://bootstrapmade.com/license/
                      Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Medicio
                    -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

  </div>
  <a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>

  <!-- Core JavaScript Files -->
  <script src="{%  static 'defence/js/jquery.min.js' %}"></script>
  <script src="{%  static 'defence/js/bootstrap.min.js' %}"></script>
  <script src="{%  static 'defence/js/jquery.easing.min.js' %}"></script>
  <script src="{%  static 'defence/js/wow.min.js' %}"></script>
  <script src="{%  static 'defence/js/jquery.scrollTo.js' %}"></script>
  <script src="{%  static 'defence/js/jquery.appear.js' %}"></script>
  <script src="{%  static 'defence/js/stellar.js' %}"></script>
  <script src="{%  static 'defence/plugins/cubeportfolio/js/jquery.cubeportfolio.min.js' %}"></script>
  <script src="{%  static 'defence/js/owl.carousel.min.js' %}"></script>
  <script src="{%  static 'defence/js/nivo-lightbox.min.js' %}"></script>
  <script src="{%  static 'defence/js/custom.js' %}"></script>

</body>

</html>